### ISSUE TITLE
C-k deletes line but C-y is not able to yank the deleted line(s)

### ISSUE THREAD

**Issue by sammy44nts** [hiro-sun/vscode-emacs#10]

**Comment by hiro-sun** [comment]
Sorry, I merged it. 
I released version 0.0.7 in vscode market, and this problem fixed.

**Comment by sammy44nts** [comment]
I'm trying to implement the kill ring as it works in emacs, see [GNU Emacs Reference Card](https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf).

Which means when C-k is pressed multiple times without moving the cursor, C-y yank all the killed lines in one time.

**Comment by sammy44nts** [comment]
See #14

**Comment by sammy44nts** [comment]
#14 not merged yet.

**Comment by hiro-sun** [comment]
Sorry for late. I merged it. Thank you very much.

**Comment by sammy44nts** [comment]
You're welcome, happy to participate.
