### ISSUE TITLE
C-k not working the way it works in emacs

### ISSUE THREAD

**Issue by sumproxy** [hiro-sun/vscode-emacs#50]
This probably is tricky to implement the proper way, but right now the second kill command doesn't kill the emty line and add it to clipboard, and subsequent yank does entirely something strange (try it!). It would be nice to have the ability to do multiple kills and paste them in a single yank.

**Comment by FreddieOliveira** [comment]
Unfortunately this project has been abandoned. Checkout
https://github.com/SebastianZaha/vscode-emacs-friendly
It's a fork of this in active development and with many improvements, including `C-k` and `M-0 C-k` properly implemented. It's available from vscode as 'vscode-emacs-friendly'

**Comment by sumproxy** [comment]
@FreddieOliveira Thank you very much for the info!
