### ISSUE TITLE
 C-x C-f doesn't do Open action

### ISSUE THREAD

**Issue by sammy44nts** [hiro-sun/vscode-emacs#8]
Hello,

First of all, thank you very much for your job on this extension guys, I love it very much.

I think because #5 is not merged yet, https://github.com/hiro-sun/vscode-emacs/blob/master/src/operation.ts#L19 does not do Open action like it should. IMHO it's a good idea to open the explorer and choose the new working folder with C-x C-f because there is no shortcut to do it and I miss it a lot.

The C-o key-binding overrides the original
{ "key": "ctrl+o", "command": "workbench.action.files.openFile" } key-binding.

**Do you think C-o is really necessary?**

**Comment by hiro-sun** [comment]
Thank you for using and issues.
I Added "workbench.action.files.openFile" key-binding in version 0.0.7
In both C-o And C-x C-f
